import {useCurrentFrame} from 'remotion';
import {designTokens} from '../lib/tokens';import type {CommonProps} from '../lib/types';import {SafeFrame} from './shared';
export type StickRigPose='idle'|'thinking'|'talking'|'pointing'|'typing'|'surprised'|'angry'|'confused'|'celebrating';
export type StickRigAction='idle'|'walk'|'run'|'turn'|'lookAt'|'pointAt'|'type'|'talk'|'fall'|'jump'|'react';
export type StickRigVariant='agent'|'operator'|'reviewer'|'human';export const stickRigVariants:StickRigVariant[]=['agent','operator','reviewer','human'];
export type StickRigProps=CommonProps&{label?:string;pose?:StickRigPose;action?:StickRigAction;variant?:StickRigVariant;showLabel?:boolean;accent?:string};
const rad=(d:number)=>d*Math.PI/180;const end=(x:number,y:number,l:number,a:number)=>({x:x+Math.sin(rad(a))*l,y:y+Math.cos(rad(a))*l});
const va=(v:StickRigVariant)=>v==='operator'?designTokens.color.positive:v==='human'?designTokens.color.muted:designTokens.color.accent;
export const StickRig=({aspect='9:16',reducedMotion=false,label='AGENTE',pose='idle',action='idle',variant='agent',showLabel=true,accent}:StickRigProps)=>{
 const frame=useCurrentFrame(),t=reducedMotion?0:frame/7,cycle=Math.sin(t),fast=Math.sin(t*1.7);const bounce=action==='jump'?-Math.abs(cycle)*70:action==='run'?-Math.abs(fast)*18:action==='walk'?-Math.abs(cycle)*8:0;const bodyRotate=action==='fall'?Math.min(78,frame*2.2):action==='react'?cycle*3:0;const turnScale=action==='turn'?(Math.cos(Math.min(Math.PI,frame/18))||.001):1;
 let lu=24,ll=12,ru=-24,rl=-12,legL=10,legR=-10,kneeL=4,kneeR=-4;
 if(pose==='thinking'){lu=120;ll=55;ru=-18;rl=-8}else if(pose==='pointing'){ru=-88;rl=2}else if(pose==='typing'){lu=68;ll=70;ru=-68;rl=-70}else if(pose==='surprised'){lu=150;ll=10;ru=-150;rl=-10}else if(pose==='angry'){lu=42;ll=-78;ru=-42;rl=78}else if(pose==='confused'){lu=108;ll=52;ru=-72;rl=-26}else if(pose==='celebrating'){lu=154;ll=12;ru=-154;rl=-12}
 if(action==='pointAt'){ru=-88;rl=2} if(action==='type'){lu=68+cycle*5;ll=70;ru=-68-cycle*5;rl=-70} if(action==='walk'||action==='run'){const amp=action==='run'?34:20;legL=cycle*amp;legR=-cycle*amp;kneeL=-cycle*amp*.55;kneeR=cycle*amp*.55;lu=-cycle*amp*.7;ru=cycle*amp*.7} if(action==='react'){lu=140+cycle*8;ru=-140-cycle*8}
 const ls={x:160,y:225},rs={x:240,y:225},le=end(ls.x,ls.y,105,lu),re=end(rs.x,rs.y,105,ru),lh=end(le.x,le.y,92,lu+ll),rh=end(re.x,re.y,92,ru+rl),lhip={x:185,y:390},rhip={x:215,y:390},lk=end(lhip.x,lhip.y,135,legL),rk=end(rhip.x,rhip.y,135,legR),lf=end(lk.x,lk.y,125,legL+kneeL),rf=end(rk.x,rk.y,125,legR+kneeR);
 const talking=pose==='talking'||action==='talk',mouth=talking&&!reducedMotion?5+Math.abs(Math.sin(frame/3))*10:talking?8:2,eye=action==='lookAt'?6:0,brow=pose==='angry'?12:pose==='confused'?7:0,stroke=designTokens.color.text,a=accent??va(variant);
 return <SafeFrame aspect={aspect} reducedMotion={reducedMotion} style={{display:'grid',placeItems:'center'}}><div style={{display:'grid',placeItems:'center',gap:28,transform:`translateY(${bounce}px) rotate(${bodyRotate}deg) scaleX(${turnScale})`,transformOrigin:'50% 70%'}}><svg width={aspect==='9:16'?650:560} height={aspect==='9:16'?980:760} viewBox="0 0 400 700" role="img" aria-label={`${label}: ${variant}, ${pose}, ${action}`}><g fill="none" stroke={stroke} strokeWidth="14" strokeLinecap="round" strokeLinejoin="round"><circle cx="200" cy="125" r="62" fill={designTokens.color.surfaceStrong} stroke={a}/><line x1="200" y1="190" x2="200" y2="390"/><line x1="160" y1="225" x2="240" y2="225"/><line x1={ls.x} y1={ls.y} x2={le.x} y2={le.y}/><line x1={le.x} y1={le.y} x2={lh.x} y2={lh.y}/><line x1={rs.x} y1={rs.y} x2={re.x} y2={re.y}/><line x1={re.x} y1={re.y} x2={rh.x} y2={rh.y}/><line x1={lhip.x} y1={lhip.y} x2={lk.x} y2={lk.y}/><line x1={lk.x} y1={lk.y} x2={lf.x} y2={lf.y}/><line x1={rhip.x} y1={rhip.y} x2={rk.x} y2={rk.y}/><line x1={rk.x} y1={rk.y} x2={rf.x} y2={rf.y}/></g><g fill={stroke}><circle cx={178+eye} cy="112" r="7"/><circle cx={222+eye} cy="112" r="7"/></g>{variant==='reviewer'&&<g fill="none" stroke={a} strokeWidth="5"><rect x="158" y="94" width="37" height="32" rx="8"/><rect x="205" y="94" width="37" height="32" rx="8"/><line x1="195" y1="108" x2="205" y2="108"/></g>}{variant==='operator'&&<path d="M150 72 Q200 30 250 72" fill="none" stroke={a} strokeWidth="10" strokeLinecap="round"/>}{brow>0&&<g stroke={stroke} strokeWidth="7" strokeLinecap="round"><line x1="164" y1={pose==='angry'?88:94} x2="190" y2={pose==='angry'?96:90}/><line x1="210" y1={pose==='angry'?96:90} x2="236" y2={pose==='angry'?88:98}/></g>}<rect x="181" y="145" width="38" height={mouth} rx="6" fill={talking?a:stroke}/><circle cx={lh.x} cy={lh.y} r="12" fill={a}/><circle cx={rh.x} cy={rh.y} r="12" fill={a}/><circle cx={le.x} cy={le.y} r="8" fill={designTokens.color.muted}/><circle cx={re.x} cy={re.y} r="8" fill={designTokens.color.muted}/><circle cx={lk.x} cy={lk.y} r="8" fill={designTokens.color.muted}/><circle cx={rk.x} cy={rk.y} r="8" fill={designTokens.color.muted}/></svg>{showLabel&&<div style={{marginTop:-100,padding:'18px 30px',borderRadius:999,border:`1px solid ${designTokens.color.line}`,background:designTokens.color.surface,fontSize:34,fontWeight:800,letterSpacing:2}}>{label}</div>}</div></SafeFrame>;
};